---
galaxy_info:
  author: nakebenihime
  description: Installs steamcmd and creates the dedicated steam user
  license: MIT
  min_ansible_version: "2.15"
  platforms:
    - name: Debian
      versions:
        - trixie
    - name: Ubuntu
      versions:
        - jammy
        - noble
        - resolute
  galaxy_tags:
    - palworld
    - steam

dependencies: []
