---
# Debian: steamcmd lives in the non-free component.
common_apt_extra_repositories:
  - "deb https://deb.debian.org/debian/ {{ ansible_distribution_release }} contrib non-free"

common_prerequisite_packages:
  - software-properties-common
  - sudo
