---
# palworld game settings (https://tech.palworldgame.com/optimize-game-balance)

palworld_settings_options:
  difficulty: None
  day_time_speed_rate: 1.0
  night_time_speed_rate: 1.0
  exp_rate: 1.0
  pal_capture_rate: 1.0
  pal_spawn_num_rate: 1.0
  pal_damage_rate_attack: 1.0
  pal_damage_rate_defense: 1.0
  player_damage_rate_attack: 1.0
  player_damage_rate_defense: 1.0
  player_stomach_decrease_rate: 1.0
  player_stamina_decrease_rate: 1.0
  player_auto_hp_regene_rate: 1.0
  player_auto_hp_regene_rate_in_sleep: 1.0
  pal_stomach_decrease_rate: 1.0
  pal_stamina_decrease_rate: 1.0
  pal_auto_hp_regene_rate: 1.0
  pal_auto_hp_regene_rate_in_sleep: 1.0
  build_object_damage_rate: 1.0
  build_object_deterioration_damage_rate: 1.0
  collection_drop_rate: 1.0
  collection_object_hp_rate: 1.0
  collection_object_respawn_speed_rate: 1.0
  enemy_drop_item_rate: 1.0
  death_penalty: All
  b_enable_player_to_player_damage: False
  b_enable_friendly_fire: False
  b_enable_invader_enemy: True
  b_active_unko: False
  b_enable_aim_assist_pad: True
  b_enable_aim_assist_keyboard: False
  drop_item_max_num: 3000
  drop_item_max_num_unko: 100
  base_camp_max_num: 128
  base_camp_worker_max_num: 15
  drop_item_alive_max_hours: 1.0
  b_auto_reset_guild_no_online_players: False
  auto_reset_guild_time_no_online_players: 72
  guild_player_max_num: 20
  pal_egg_default_hatching_time: 72
  work_speed_rate: 1.0
  b_is_multiplay: False
  b_is_pvp: False
  b_can_pickup_other_guild_death_penalty_drop: False
  b_enable_non_login_penalty: True
  b_enable_fast_travel: True
  b_is_start_location_select_by_map: True
  b_exist_player_after_logout: False
  b_enable_defense_other_guild_player: False
  coop_player_max_num: 4
  server_player_max_num: 32
  server_name: "Palworld Dedicated Server on LINUX"
  server_description: "The Palworld Dedicated Server on Linux is provisioned using Ansible and Terraform. For the latest updates, follow: https://github.com/Nakebenihime/palworld-dedicated-server-linux.git."
  admin_password: ""
  server_password: ""
  public_port: '{{ firewall_palworld_port }}'
  public_ip: "{{ ansible_facts['default_ipv4']['address'] }}"
  rcon_enabled: False
  rcon_port: 25575
  region: ""
  b_use_auth: True
  ban_list_url: "https://api.palworldgame.com/api/banlist.txt"
