---
galaxy_info:
  author: nakebenihime
  description: Installs, configures and runs the Palworld dedicated server as a systemd service
  license: MIT
  min_ansible_version: "2.15"
  platforms:
    - name: Debian
      versions:
        - bookworm
    - name: Ubuntu
      versions:
        - jammy
        - noble
  galaxy_tags:
    - palworld
    - gameserver

dependencies: []
