---
# palworld tasks

- name: palworld > create server directory
  ansible.builtin.file:
    path: '{{ steamcmd_server_directory }}'
    state: directory
    owner: '{{ steamcmd_user }}'
    group: '{{ steamcmd_user_group }}'
    mode: '0750'
  become: true

- name: palworld > download palworld dedicated server via steamcmd
  ansible.builtin.command: >
    {{ steamcmd_download_command }}
  args:
    chdir: '{{ steamcmd_server_directory }}'
  become: true
  become_user: '{{ steamcmd_user }}'
  changed_when: false
  environment:
    HOME: '{{ steamcmd_user_home }}'

- name: palworld > check if saved directory exists
  ansible.builtin.stat:
    path: '{{ palworld_save_directory }}'
  register: __palworld_saved_dir_exists

- name: palworld > start palworld to generate configuration files
  ansible.builtin.command: >
    timeout 20s ./PalServer.sh -useperfthreads -NoAsyncLoadingThread -UseMultithreadForDS
  args:
    chdir: '{{ steamcmd_server_directory }}'
  become: true
  become_user: '{{ steamcmd_user }}'
  changed_when: false
  failed_when: false  # (timeout rc == 124)
  environment:
    HOME: '{{ steamcmd_user_home }}'
  when: not __palworld_saved_dir_exists.stat.exists

- name: palworld > retrieve palworld.service status
  ansible.builtin.systemd_service:
    name: palworld
  register: __palworld_status

- name: palworld > stop palworld.service if running
  ansible.builtin.systemd_service:
    name: palworld
    state: stopped
  when: __palworld_status.status.ActiveState == 'active'

- name: palworld > modify 'PalworldSettings.ini' configuration file using j2
  ansible.builtin.template:
    src: templates/palworld_settings.j2
    dest: '{{ palworld_settings_file }}'
    owner: '{{ steamcmd_user }}'
    group: '{{ steamcmd_user_group }}'
    mode: '0644'
    follow: false
  register: __template_palworld_settings_status
  changed_when: __template_palworld_settings_status.changed

- name: palworld > create/modify palworld.service
  ansible.builtin.template:
    src: templates/palworld_systemd_service.j2
    dest: /etc/systemd/system/palworld.service
    mode: '0644'
  register: __template_palworld_systemd_status

- name: palworld > create/modify palworld-maintenance.sh
  ansible.builtin.template:
    src: templates/palworld_maintenance_script.j2
    dest: '{{ steamcmd_server_directory }}/palworld-maintenance.sh'
    owner: '{{ steamcmd_user }}'
    group: '{{ steamcmd_user_group }}'
    mode: '0750'
  register: __template_palworld_maintenance_script_status

- name: palworld > reload daemon to make sure systemd has read any changes
  ansible.builtin.systemd_service:
    name: palworld
    daemon_reload: true
  when: >
    __template_palworld_systemd_status.changed or
    __template_palworld_settings_status.changed or
    __template_palworld_maintenance_script_status.changed
